name: Build and Push Docker Images
concurrency:
  group: docker-build-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
on:
  push:
    branches:
      - main
    tags:
      - 'v*'

jobs:
  build-and-push-backend:
    runs-on: ubuntu-latest
    env:
      BACKEND_IMAGE: intelloop/atlas-cmms-backend
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Determine Docker tag
        id: vars
        run: |
          if [[ "${GITHUB_REF}" == refs/tags/v* ]]; then
            TAG_NAME="${GITHUB_REF#refs/tags/}"
          else
            TAG_NAME="latest"
          fi
          echo "DOCKER_TAG=$TAG_NAME" >> $GITHUB_OUTPUT

      - name: Build and push backend image
        uses: docker/build-push-action@v6
        with:
          context: ./api
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ${{ env.BACKEND_IMAGE }}:${{ steps.vars.outputs.DOCKER_TAG }}

  build-and-push-frontend:
    runs-on: ubuntu-latest
    env:
      FRONTEND_IMAGE: intelloop/atlas-cmms-frontend
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Determine Docker tag
        id: vars
        run: |
          if [[ "${GITHUB_REF}" == refs/tags/v* ]]; then
            TAG_NAME="${GITHUB_REF#refs/tags/}"
          else
            TAG_NAME="latest"
          fi
          echo "DOCKER_TAG=$TAG_NAME" >> $GITHUB_OUTPUT

      - name: Build and push frontend image
        uses: docker/build-push-action@v6
        with:
          context: ./frontend
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ${{ env.FRONTEND_IMAGE }}:${{ steps.vars.outputs.DOCKER_TAG }}
